version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - server
      - client

  server:
    build:
      context: server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./server:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://sofretim:sofretimCarSecurity@postgres:5432/sofretim'
  
  client:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 8001:4200
    volumes:
      - './client:/app:cached'
      - './client/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development


volumes:
  db-data:
